version: '2'
services:
    db:
        image: mysql:5.6
        volumes:
            - "./.data/db:/var/lib/mysql"
            - "./database:/docker-entrypoint-initdb.d"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
    web:
        image: orsolin/docker-php-5.3-apache
        volumes:
            - ".:/var/www/html"
        ports:
            - 3000:80
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 3001:80